runtime: python27
api_version: 1
service: default
threadsafe: true
handlers:
  - url: /
    static_files: dist/socks/index.html
    upload: dist/socks/index.html
    secure: always
  - url: /
    static_dir: dist/socks
    secure: always
